version: 2
jobs:
  visual_test:
    docker:
    - image: cypress/base:10
    steps:
    - checkout: {}
    - restore_cache:
        keys:
        - myapps-{{ .Branch }}-{{ checksum "package.json" }}
    - run: npm install --save-dev && npm test
    - save_cache:
        key: myapp-{{ .Branch }}-{{ checksum "package.json" }}
        paths:
        - ~/npm
        - ~/.cache
    - store_artifacts:
        path: /root/project/cypress/snapshots
        destination: visual-regression
    - store_artifacts:
        path: /root/project/cypress/videos/Visual-test3
        destination: visual-regression

  e2e_test:
    docker:
    - image: cypress/base:8
    steps:
    - checkout: {}
    - restore_cache:
        keys:
        - myapps2-{{ .Branch }}-{{ checksum "package.json" }}
    - run: npm install
    - run: ./node_modules/.bin/cypress run --spec 'cypress/integration/e2e_test/**/*'
        --browser electron
    - save_cache:
        key: myapp-{{ .Branch }}-{{ checksum "package.json" }}
        paths:
        - ~/npm
        - ~/.cache
    - store_artifacts:
        path: /root/project/cypress/snapshots
        destination: visual-regression
    - store_artifacts:
        path: /root/project/cypress/videos/Visual-test3
        destination: visual-regression    
  Visual-test2:
    docker:
    - image: cypress/base:8
    steps:
    - checkout: {}
    - restore_cache:
        keys:
        - myapps2-{{ .Branch }}-{{ checksum "package.json" }}
    - run: npm install
    - run: ./node_modules/.bin/cypress run --spec 'cypress/integration/Visualtest2/**/*'
        --browser electron
    - save_cache:
        key: myapp-{{ .Branch }}-{{ checksum "package.json" }}
        paths:
        - ~/npm
        - ~/.cache
    - store_artifacts:
        path: /root/project/cypress/snapshots
        destination: visual-regression
    - store_artifacts:
        path: /root/project/cypress/videos/Visual-test3
        destination: visual-regression    
  Visual-test3:
    docker:
    - image: cypress/base:8
    steps:
    - checkout: {}
    - restore_cache:
        keys:
        - myapps2-{{ .Branch }}-{{ checksum "package.json" }}
    - run: npm install
    - run: ./node_modules/.bin/cypress run --spec 'cypress/integration/Visual-test3/**/*'
        --browser electron
    - save_cache:
        key: myapp-{{ .Branch }}-{{ checksum "package.json" }}
        paths:
        - ~/npm
        - ~/.cache
    - store_artifacts:
        path: /root/project/cypress/snapshots
        destination: visual-regression
    - store_artifacts:
        path: /root/project/cypress/videos/Visual-test3
        destination: visual-regression    
  Visual-test4:
    docker:
    - image: cypress/base:8
    steps:
    - checkout: {}
    - restore_cache:
        keys:
        - myapps2-{{ .Branch }}-{{ checksum "package.json" }}
    - run: npm install
    - run: ./node_modules/.bin/cypress run --spec 'cypress/integration/Visual-test4/**/*'
        --browser electron
    - save_cache:
        key: myapp-{{ .Branch }}-{{ checksum "package.json" }}
        paths:
        - ~/npm
        - ~/.cache
    - store_artifacts:
        path: /root/project/cypress/snapshots
        destination: visual-regression
    - store_artifacts:
        path: /root/project/cypress/videos/Visual-test3
        destination: visual-regression    
workflows:
  version: 2
  build_and_test:
    jobs:
    - Visual-test2
    - Visual-test3
    - Visual-test4
    - visual_test
